# fly.toml app configuration file generated for tfgfinder-geiade-api on 2025-02-09T11:26:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tfgfinder-geiade-api'
primary_region = 'mad'
swap_size_mb = 512

[build]

[env]
  JAVA_OPTS = '-XX:MaxRAM=70m'
  SERVER_FORWARD_HEADERS_STRATEGY = 'NATIVE'
  SPRING_PROFILES_ACTIVE = 'flyio'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  size = 'shared-cpu-1x'
