allowed-origins: "https://tfgfinder-geiade.netlify.app,https://deploy-preview-*--tfgfinder-geiade.netlify.app"

logging:
    level:
        org:
            hibernate: error
            springframework.core: error
            springframework.web: error
        root: error
